name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireFlow
          path: ./build/libs/FireFlow-*-all.jar